// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlrbnvdyilkfbedzgbfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRscmJudmR5aWxrZmJlZHpnYmZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzM2NTYsImV4cCI6MjA3MzAwOTY1Nn0.HRuO77Sg0Mx95TQZIPjPza7wvBZ22-1_rCqBtlEGrmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});